name: user_service
description: Cyberzone user service.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

dependencies:
  shelf: any
  shelf_router: any
  postgres: ^2.6.3
  dart_jsonwebtoken: ^3.3.0
  shelf_swagger_ui: ^1.0.0
  http: ^1.2.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
